"""
HTML Report Generator
Creates comprehensive HTML reports for test execution results
"""
import os
import json
import logging
from typing import List, Dict, Any, Tuple
from datetime import datetime
from models import (GeneratedTestCase, ReviewResult, TestExecutionResult, 
                    TestSuiteResult)
from config.settings import RejectionReason, TestStatus

logger = logging.getLogger(__name__)

class HTMLReportGenerator:
    """Generate comprehensive HTML test reports"""
    
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def generate_report(self, 
                       test_results: List[Tuple],
                       execution_results: List[TestExecutionResult],
                       suite_id: str = "test_suite") -> str:
        """
        Generate comprehensive HTML report
        
        Args:
            test_results: List of (GeneratedTestCase, ReviewResult, rejection_history) tuples
            execution_results: List of execution results
            suite_id: Suite identifier
            
        Returns:
            Path to generated HTML report
        """
        html_content = self._build_html(test_results, execution_results, suite_id)
        
        report_path = os.path.join(self.output_dir, f"{suite_id}_report.html")
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info(f"Report generated: {report_path}")
        return report_path
    
    def _build_html(self, test_results: List[Tuple], 
                   execution_results: List[TestExecutionResult],
                   suite_id: str) -> str:
        """Build the complete HTML report"""
        
        # Calculate statistics
        total_tests = len(test_results)
        approved_tests = sum(1 for _, review, _ in test_results if review.is_approved)
        rejected_tests = total_tests - approved_tests
        
        passed_tests = sum(1 for r in execution_results if r.status == TestStatus.PASSED)
        failed_tests = sum(1 for r in execution_results if r.status == TestStatus.FAILED)
        
        pass_rate = (passed_tests / len(execution_results) * 100) if execution_results else 0
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QA Test Report - {suite_id}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>QA Test Execution Report</h1>
            <p class="report-id">Suite ID: {suite_id}</p>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>
        
        <div class="summary-section">
            <h2>Executive Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Total Tests</h3>
                    <p class="metric">{total_tests}</p>
                </div>
                <div class="summary-card">
                    <h3>Approved</h3>
                    <p class="metric approved">{approved_tests}</p>
                </div>
                <div class="summary-card">
                    <h3>Rejected</h3>
                    <p class="metric rejected">{rejected_tests}</p>
                </div>
                <div class="summary-card">
                    <h3>Pass Rate</h3>
                    <p class="metric">
                        <span class="{'passed' if pass_rate >= 80 else 'warning'}">{pass_rate:.1f}%</span>
                    </p>
                </div>
            </div>
            
            <div class="progress-section">
                <h3>Test Results Distribution</h3>
                <div class="progress-bar">
                    <div class="progress-passed" style="width: {pass_rate}%"></div>
                </div>
                <p class="progress-text">
                    {passed_tests} Passed | {failed_tests} Failed
                </p>
            </div>
        </div>
        
        <div class="details-section">
            <h2>Test Details</h2>
            
            {self._generate_test_details_section(test_results, execution_results)}
            
            {self._generate_rejection_section(test_results)}
            
            {self._generate_execution_logs_section(execution_results)}
        </div>
        
        <footer>
            <p>Report generated by QA Testing Agent</p>
        </footer>
    </div>
</body>
</html>"""
        
        return html
    
    def _generate_test_details_section(self, test_results: List[Tuple],
                                      execution_results: List[TestExecutionResult]) -> str:
        """Generate test details section"""
        html = '<div class="test-details">'
        
        for idx, (generated_test, review_result, rejection_history) in enumerate(test_results, 1):
            # Find corresponding execution result
            exec_result = next(
                (r for r in execution_results if r.test_case_id == generated_test.test_case_id),
                None
            )
            
            status_class = "passed" if exec_result and exec_result.status == TestStatus.PASSED else "failed"
            status_text = exec_result.status.value if exec_result else "NOT EXECUTED"
            
            html += f"""
            <div class="test-item {status_class}">
                <div class="test-header">
                    <h3>Test {idx}: {generated_test.test_case_id}</h3>
                    <span class="status-badge {status_class}">{status_text}</span>
                </div>
                
                <div class="test-content">
                    <div class="test-section">
                        <h4>Review Status</h4>
                        <p>
                            <strong>Approved:</strong> 
                            <span class="{'approved' if review_result.is_approved else 'rejected'}">
                                {'Yes' if review_result.is_approved else 'No'}
                            </span>
                        </p>
                        {f'<p><strong>Rejection Reason:</strong> {review_result.rejection_reason.value}</p>' if not review_result.is_approved else ''}
                        {f'<p><strong>Details:</strong> {review_result.rejection_details}</p>' if review_result.rejection_details else ''}
                    </div>
                    
                    {self._generate_test_data_section(generated_test)}
                    
                    {self._generate_execution_details(exec_result) if exec_result else ''}
                </div>
            </div>
            """
        
        html += '</div>'
        return html
    
    def _generate_test_data_section(self, generated_test: GeneratedTestCase) -> str:
        """Generate test data section"""
        test_data_json = json.dumps(generated_test.test_data, indent=2)
        
        return f"""
        <div class="test-section">
            <h4>Test Data</h4>
            <pre class="code-block">{test_data_json}</pre>
        </div>
        """
    
    def _generate_execution_details(self, exec_result: TestExecutionResult) -> str:
        """Generate execution details"""
        html = f"""
        <div class="test-section">
            <h4>Execution Details</h4>
            <p><strong>Duration:</strong> {exec_result.duration_seconds:.2f}s</p>
        """
        
        if exec_result.error_message:
            html += f'<p><strong>Error:</strong> <pre>{exec_result.error_message}</pre></p>'
        
        if exec_result.screenshot_path:
            html += f'<p><strong>Screenshot:</strong> <a href="{exec_result.screenshot_path}">View</a></p>'
        
        html += '</div>'
        return html
    
    def _generate_rejection_section(self, test_results: List[Tuple]) -> str:
        """Generate rejection details section"""
        rejected = [r for r in test_results if not r[1].is_approved]
        
        if not rejected:
            return '<div class="rejection-section"><p>No rejected tests</p></div>'
        
        html = '<div class="rejection-section"><h2>Rejection Details</h2>'
        
        for generated_test, review_result, rejection_history in rejected:
            html += f"""
            <div class="rejection-item">
                <h3>{generated_test.test_case_id}</h3>
                <div class="rejection-reason">
                    <p><strong>Primary Reason:</strong> {review_result.rejection_reason.value}</p>
                    <p><strong>Details:</strong> {review_result.rejection_details}</p>
                </div>
                
                <div class="rejection-history">
                    <h4>Rejection History</h4>
                    {self._generate_rejection_history(rejection_history)}
                </div>
                
                <div class="improvement-suggestions">
                    <h4>Improvement Suggestions</h4>
                    <p>{review_result.improvement_suggestions}</p>
                </div>
            </div>
            """
        
        html += '</div>'
        return html
    
    def _generate_rejection_history(self, history: List[Dict]) -> str:
        """Generate rejection attempt history"""
        if not history:
            return '<p>No rejection history</p>'
        
        html = '<ul>'
        for attempt in history:
            html += f"""
            <li>
                Attempt {attempt['attempt']}: {attempt['reason']}
                <br><small>{attempt['details']}</small>
            </li>
            """
        html += '</ul>'
        return html
    
    def _generate_execution_logs_section(self, execution_results: List[TestExecutionResult]) -> str:
        """Generate execution logs section"""
        html = '<div class="logs-section"><h2>Execution Logs</h2>'
        
        for result in execution_results:
            if result.logs:
                html += f"""
                <div class="log-item">
                    <h3>{result.test_name}</h3>
                    <details>
                        <summary>View Logs</summary>
                        <pre>{result.logs[0][:500]}</pre>
                    </details>
                </div>
                """
        
        html += '</div>'
        return html
    
    def _get_css(self) -> str:
        """Get CSS styles"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        
        header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        
        .report-id {
            font-size: 0.9em;
            opacity: 0.9;
        }
        
        .timestamp {
            font-size: 0.85em;
            opacity: 0.8;
            margin-top: 5px;
        }
        
        .summary-section {
            padding: 40px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        
        .summary-section h2 {
            margin-bottom: 20px;
            color: #667eea;
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .summary-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            border-left: 4px solid #667eea;
        }
        
        .summary-card h3 {
            color: #666;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
        }
        
        .metric {
            font-size: 2em;
            font-weight: bold;
            color: #333;
        }
        
        .metric.approved {
            color: #28a745;
        }
        
        .metric.rejected {
            color: #dc3545;
        }
        
        .metric .passed {
            color: #28a745;
        }
        
        .progress-section {
            background: white;
            padding: 20px;
            border-radius: 8px;
        }
        
        .progress-bar {
            height: 30px;
            background: #e9ecef;
            border-radius: 4px;
            overflow: hidden;
            margin: 15px 0;
        }
        
        .progress-passed {
            height: 100%;
            background: linear-gradient(90deg, #28a745, #20c997);
            transition: width 0.3s ease;
        }
        
        .details-section {
            padding: 40px;
        }
        
        .details-section h2 {
            color: #667eea;
            margin-bottom: 20px;
        }
        
        .test-details {
            display: grid;
            gap: 20px;
        }
        
        .test-item {
            border: 2px solid #e9ecef;
            border-radius: 8px;
            overflow: hidden;
            transition: all 0.3s ease;
        }
        
        .test-item.passed {
            border-left: 5px solid #28a745;
        }
        
        .test-item.failed {
            border-left: 5px solid #dc3545;
        }
        
        .test-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        
        .test-header h3 {
            margin: 0;
            font-size: 1.1em;
        }
        
        .status-badge {
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: bold;
            text-transform: uppercase;
        }
        
        .status-badge.passed {
            background: #d4edda;
            color: #155724;
        }
        
        .status-badge.failed {
            background: #f8d7da;
            color: #721c24;
        }
        
        .test-content {
            padding: 20px;
        }
        
        .test-section {
            margin-bottom: 20px;
        }
        
        .test-section:last-child {
            margin-bottom: 0;
        }
        
        .test-section h4 {
            color: #667eea;
            margin-bottom: 10px;
            font-size: 0.95em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .code-block {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 4px;
            padding: 15px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 0.85em;
        }
        
        .rejection-section {
            background: #fff3cd;
            border: 1px solid #ffc107;
            border-radius: 8px;
            padding: 20px;
            margin-top: 20px;
        }
        
        .rejection-item {
            background: white;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 15px;
            border-left: 4px solid #dc3545;
        }
        
        .rejection-reason {
            background: #f8d7da;
            padding: 10px;
            border-radius: 4px;
            margin: 10px 0;
        }
        
        .improvement-suggestions {
            background: #e7f3ff;
            padding: 10px;
            border-radius: 4px;
            margin: 10px 0;
        }
        
        .logs-section {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-top: 20px;
        }
        
        .log-item {
            background: white;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 10px;
        }
        
        footer {
            text-align: center;
            padding: 20px;
            background: #f8f9fa;
            color: #666;
            font-size: 0.9em;
        }
        
        .approved {
            color: #28a745;
            font-weight: bold;
        }
        
        .rejected {
            color: #dc3545;
            font-weight: bold;
        }
        """
