import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: REGRESSION - Verify other features work post filter reload
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_verify_features_post_filter_reload(page):

    try:
        # Login to the application
        _login(page)

        # Navigate to the filter section and apply an OR operator within filters
        page.click("[data-testid='filter-section']")
        page.click("[data-testid='filter-or-operator']")
        page.wait_for_load_state("networkidle")

        # Reload the filters with the OR operator applied
        page.click("[data-testid='reload-filters-btn']")
        page.wait_for_load_state("networkidle")

        # Verify the application provides feedback that the filter has been reloaded with the OR operator
        feedback_locator = page.locator("[data-testid='filter-reload-feedback']")
        assert feedback_locator.text_content().strip() == "Filters reloaded with OR operator", "Expected feedback not found or incorrect."

        # Use another unrelated feature to ensure it works post filter reload
        page.click("[data-testid='unrelated-feature-btn']")
        page.wait_for_load_state("networkidle")

        # Expected: The unrelated feature should work as expected
        unrelated_feature_result = page.locator("[data-testid='unrelated-feature-result']")
        assert unrelated_feature_result.is_visible(), "Unrelated feature is not working as expected post filter reload."

    except Exception:
        page.screenshot(path="failure_test_verify_features_post_filter_reload.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_verify_features_post_filter_reload(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/verify_features_post_filter_reload_20260217_101340.png")
        _exit = 1
    sys.exit(_exit)
