import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ERROR_FAILURE - Handling errors during filter panel reload
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_filter_panel_reload_error_handling(page):

    try:
        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)

        # Navigate to the page where the filter panel is located
        # Assuming the filter panel is on the dashboard for this example
        page.goto(f"{settings.BASE_URL}/dashboard")
        page.wait_for_load_state("networkidle")

        # Simulate a network error on filter panel reload
        page.route("**/api/filter/reload", lambda route: route.abort("failed"))

        # Trigger the filter panel reload by applying the OR operator
        # Assuming there's a button or link to apply the OR operator
        page.get_by_role("button", name="Apply OR").click()

        # Wait for the error message to appear
        page.wait_for_load_state("networkidle")

        # Verify that a nonintrusive error message is displayed
        error_message = page.get_by_text("Error reloading filters", exact=False)
        expect(error_message).to_be_visible()

        # Verify that the user's filter selections are preserved
        # Assuming there's a way to check a specific filter selection, like a checkbox or a specific filter value
        filter_selection = page.locator("input[name='filter-checkbox'][checked]")
        expect(filter_selection).to_have_count(1)  # Assuming one filter was selected before the error

    except Exception:
        page.screenshot(path="failure_test_filter_panel_reload_error_handling.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_filter_panel_reload_error_handling(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/filter_panel_reload_error_handling_20260217_134532.png")
        _exit = 1
    sys.exit(_exit)
