import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: BUSINESS_RULES - Filter options based on metadata and previous filters
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_filter_options_based_on_metadata(page):

    try:
        # Navigate to the base URL and wait for the page to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Apply the first filter
        page.locator("[data-testid='filter-1']").click()
        page.wait_for_load_state("networkidle")

        # Select the OR operator
        page.locator("[data-testid='operator-or']").click()
        page.wait_for_load_state("networkidle")

        # Assert that the filter options are updated based on the metadata and previously applied filters
        # This is a generic check to ensure that at least one expected filter option is present
        assert page.locator("[data-testid='updated-filter-option']").count() > 0, "Expected updated filter options are not displayed"

        # Optionally, check for specific filter options that should be present
        # This step assumes knowledge of what filter options should be available after the previous steps
        expected_filters = ["Updated Option 1", "Updated Option 2"]
        for filter_option in expected_filters:
            assert page.locator(f"text={filter_option}").count() > 0, f"Filter option '{filter_option}' is not displayed as expected"

        # Additional step to ensure the OR operator logic is applied correctly by checking the results
        # This step assumes the application displays some form of results or data that changes based on the applied filters
        page.locator("[data-testid='apply-filters']").click()
        page.wait_for_load_state("networkidle")
        assert page.locator("[data-testid='filter-result']").count() > 0, "No results displayed after applying filters with OR operator"

    except Exception:
        page.screenshot(path="failure_test_filter_options_based_on_metadata.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_filter_options_based_on_metadata(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/filter_options_based_on_metadata_20260218_072102.png")
        _exit = 1
    sys.exit(_exit)
