import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ASYNC_TIMING - Loader state and seamless UI update
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_loader_state_and_ui_update(page):

    try:
        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)

        # Wait for the page to load completely after login
        page.wait_for_load_state("networkidle")

        # Capture the initial count of tags before selecting a new tag
        initial_tags = page.locator("[data-testid='tag']").count()

        # Select a tag by clicking on it
        page.get_by_text("Tag Name", exact=False).click()

        # Wait for the loader to appear and then disappear indicating loading state
        page.get_by_role("status", name="Loading").wait_for(state="visible")
        page.get_by_role("status", name="Loading").wait_for(state="hidden")

        # Assert the UI has been updated by checking the count of tags has increased
        final_tags = page.locator("[data-testid='tag']").count()
        assert final_tags > initial_tags, "Expected more tags to be displayed after loading"

        # Verify the UI updated without visual glitches by checking for the presence of an additional specific tag
        expect(page.get_by_text("New Tag", exact=False)).to_be_visible()

    except Exception:
        page.screenshot(path="failure_test_loader_state_and_ui_update.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_loader_state_and_ui_update(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/loader_state_and_ui_update_20260217_101338.png")
        _exit = 1
    sys.exit(_exit)
