import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: HAPPY_PATH - Filter assets using a single tag and auto-populate additional tags
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_single_tag_selection_and_auto_populate_additional_tags(page):

    try:
        # Navigate to the base URL
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Wait for the filter panel to load and select Tag A
        tagA = page.locator("text=Tag A").first()
        tagA.click()

        # Wait for the assets to be filtered and displayed
        page.wait_for_load_state("networkidle")

        # Assert that assets related to Tag A are displayed
        assets = page.locator("[data-testid='asset']")
        assert assets.count() > 0, "No assets displayed for Tag A"

        # Assert that additional tags related to the displayed assets are shown in the filter panel
        additionalTags = page.locator("[data-testid='additional-tag']")
        assert additionalTags.count() > 0, "No additional tags displayed for assets related to Tag A"

        # Verify at least one of the expected additional tags is present
        expectedAdditionalTag = "Additional Tag 1"
        assert page.locator(f"text={expectedAdditionalTag}").count() > 0, f"{expectedAdditionalTag} not found in additional tags"

    except Exception:
        page.screenshot(path="failure_test_single_tag_selection_and_auto_populate_additional_tags.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_single_tag_selection_and_auto_populate_additional_tags(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/single_tag_selection_and_auto_populate_a_20260217_125831.png")
        _exit = 1
    sys.exit(_exit)
