import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: BUSINESS_RULES - Ensuring no tag loss among top 20 tags
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_verify_no_tag_loss_in_top_20(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Navigate to the page where tags are displayed and wait for it to load
        page.goto(f"{settings.BASE_URL}/tags")
        page.wait_for_load_state("networkidle")

        # Select a tag that results in more than 20 additional tags being applicable
        # Assuming there's a way to select such a tag, e.g., by clicking on it
        page.locator("text=Select Tag").click()
        page.wait_for_load_state("networkidle")

        # Count the number of tags displayed after the selection
        tags_displayed = page.locator("[data-testid='tag']").count()

        # Verify that exactly 20 tags are displayed
        assert tags_displayed == 20, f"Expected 20 tags to be displayed, but found {tags_displayed}"

        # Verify that the top 20 tags are displayed based on some ranking logic
        # This step assumes there's a way to identify that the correct tags are displayed, e.g., by their specific data-testid or content
        # For simplicity, this step will be a generic check to ensure that no additional tags are displayed beyond the top 20
        for i in range(tags_displayed):
            tag = page.locator(f"[data-testid='tag']:nth-of-type({i+1})")
            assert tag, f"Tag {i+1} is not displayed or does not exist."

        # Optionally, verify no additional tags are present beyond the expected 20
        unexpected_tag = page.locator("[data-testid='tag']:nth-of-type(21)").is_visible()
        assert not unexpected_tag, "More than 20 tags are displayed, which violates the business rule."
    except Exception:
        page.screenshot(path="failure_test_verify_no_tag_loss_in_top_20.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_verify_no_tag_loss_in_top_20(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/verify_no_tag_loss_in_top_20_20260217_101337.png")
        _exit = 1
    sys.exit(_exit)
