import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: UI_UX_CONSISTENCY - Smooth reload without UI reset
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_smooth_reload_no_ui_reset(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Ensure the page has loaded completely after login
        page.wait_for_load_state("networkidle")

        # Interact with the filter panel, assuming it's identifiable by a specific role or label
        filter_panel = page.locator("[data-testid='filter-panel']")
        assert filter_panel.is_visible(), "Filter panel is not visible"

        # Select the OR operator from the filter options
        or_operator_option = filter_panel.locator("[data-testid='operator-or']")
        or_operator_option.click()

        # Apply the filter, assuming a button with a specific test ID exists for this action
        apply_filter_button = filter_panel.locator("[data-testid='apply-filter-btn']")
        apply_filter_button.click()

        # Wait for the filter panel to reload
        page.wait_for_load_state("networkidle")

        # Assertions to ensure the UI has not reset
        # Check if the filter panel is still visible and in the expected state
        assert filter_panel.is_visible(), "Filter panel is not visible after reload"
        # Verify the OR operator is still selected
        assert or_operator_option.is_checked(), "OR operator is not selected after reload"
        # Check if search results are still present, assuming identifiable by a specific role or label
        search_results = page.locator("[data-testid='search-results']")
        assert search_results.count() > 0, "Search results were cleared after reload"

    except Exception:
        page.screenshot(path="failure_test_smooth_reload_no_ui_reset.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_smooth_reload_no_ui_reset(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/smooth_reload_no_ui_reset_20260217_124658.png")
        _exit = 1
    sys.exit(_exit)
