import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: PERFORMANCE_SCALE - Test with large number of filters
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_performance_with_large_filter_set(page):

    try:
        start_time = time.time()
        _login(page)
        page.goto(settings.BASE_URL + "/dataset")

        # Assuming the application has a way to apply filters through a UI component
        # Apply the first filter
        page.locator("[data-testid='filter-add']").click()
        page.locator("[data-testid='filter-field']").fill("First Filter")
        page.locator("[data-testid='filter-value']").fill("Value1")
        page.locator("[data-testid='submit-btn']").click()

        # Wait for the filter panel to reload
        page.wait_for_load_state("networkidle")

        # Apply multiple filters using the OR operator
        for i in range(2, 21):  # Example: Apply 20 filters in total
            page.locator("[data-testid='filter-add']").click()
            page.locator("[data-testid='filter-operator-or']").click()
            page.locator("[data-testid='filter-field']").fill(f"Filter{i}")
            page.locator("[data-testid='filter-value']").fill(f"Value{i}")
            page.locator("[data-testid='submit-btn']").click()
            page.wait_for_load_state("networkidle")

        end_time = time.time()

        # Check if the filter panel reloads within acceptable performance thresholds
        assert (end_time - start_time) < 10, f"Filter panel reload took {end_time - start_time:.2f}s, exceeding performance threshold."

    except Exception:
        page.screenshot(path="failure_test_performance_with_large_filter_set.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_performance_with_large_filter_set(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/performance_with_large_filter_set_20260217_101340.png")
        _exit = 1
    sys.exit(_exit)
