import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: PERFORMANCE_SCALE - Large number of tags and assets
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    # Step 1: Click Filter, Expand Tags
    page.get_by_role("button", name=re.compile(r"Filter, Expand Tags", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")


def test_performance_with_large_number_of_tags_and_assets(page):

    try:
        _login(page)
        _precondition(page)  # This sets up the UI for the test, including expanding the Tags section.

        # Start timing after the setup is complete.
        start_time = time.time()

        # Simulate selecting a tag that returns a large number of assets.
        # Assuming there's a specific tag designed for performance testing.
        page.locator("[data-testid='tag-selector']").click()
        page.locator("text=HighVolumeTag").click()

        # Wait for the assets to load. This is crucial for performance measurement.
        page.wait_for_load_state("networkidle")

        # Stop timing after assets have loaded.
        end_time = time.time()

        # Calculate the time taken to load the assets.
        load_time = end_time - start_time

        # Assert that the load time is acceptable, e.g., less than 5 seconds.
        assert load_time < 5, f"Assets took too long to load: {load_time:.2f}s"

        # Optionally, verify that the assets and their tags are displayed correctly.
        # This step is more about functionality than performance, but it's good to check that the data loads correctly.
        assets_displayed = page.locator("[data-testid='asset-card']").count()
        assert assets_displayed > 0, "No assets displayed"

        # Check that at least one asset has multiple tags displayed.
        # This verifies that additional tags are auto-populated without significant delay.
        multiple_tags_displayed = page.locator("[data-testid='asset-card'] [data-testid='tag-list']:has-text(',')").count()
        assert multiple_tags_displayed > 0, "Assets do not display multiple tags"

    except Exception:
        page.screenshot(path="failure_test_performance_with_large_number_of_tags_and_assets.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_performance_with_large_number_of_tags_and_assets(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/performance_with_large_number_of_tags_an_20260218_143033.png")
        _exit = 1
    sys.exit(_exit)
