import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: PERFORMANCE_SCALE - Handling large number of tags efficiently
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_performance_with_large_tag_volume(page):

    try:
        _login(page)
        page.wait_for_load_state("networkidle")

        # Navigate to the tags or assets page where tags can be selected
        page.goto(f"{settings.BASE_URL}/tags")
        page.wait_for_load_state("networkidle")

        # Start performance timing before selecting a tag
        start_time = time.time()

        # Select a specific tag from a list or dropdown that is known to have a large number of distinct tags
        page.get_by_role("combobox").click()
        page.get_by_text("SpecificTag", exact=False).click()

        # Wait for the related tags or assets to load based on the selected tag
        page.wait_for_load_state("networkidle")

        # End performance timing after the related tags are loaded
        end_time = time.time()

        # Assert that the loading time is within an acceptable range, indicating no significant performance degradation
        assert (end_time - start_time) < 5, f"Loading time exceeded expected threshold: {end_time - start_time:.2f}s"

        # Verify that additional related tags are auto-populated in the filter as expected
        auto_populated_tags = page.locator("[data-testid='related-tags']")
        assert auto_populated_tags.count() > 0, "Expected additional related tags to be auto-populated"

        # Perform a final check to ensure that the system's response and display of tags are as expected
        displayed_tags = page.locator("[data-testid='displayed-tags']")
        expect(displayed_tags).to_have_count_greater_than(0, "Expected to find displayed tags after selecting a specific tag")

    except Exception:
        page.screenshot(path="failure_test_performance_with_large_tag_volume.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_performance_with_large_tag_volume(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/performance_with_large_tag_volume_20260217_101338.png")
        _exit = 1
    sys.exit(_exit)
