import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

def _dump_debug():
    global _page
    if not _page:
        return
    try:
        _page.wait_for_load_state('domcontentloaded', timeout=2000)
    except Exception:
        pass
    try:
        print(f"DEBUG_URL: {_page.url}")
    except Exception:
        pass

"""
Test: BOUNDARY_EMPTY - No filters applied initially
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("domcontentloaded")

    def _fill_first(locators, value, label):
        last_err = None
        for loc in locators:
            try:
                target = loc.first
                expect(target).to_be_visible(timeout=3000)
                target.fill(value)
                return
            except Exception as e:
                last_err = e
        raise RuntimeError(f"Could not find {label} field") from last_err

    _fill_first(
        [
            page.get_by_label(settings.EMAIL_FIELD_LABEL),
            page.get_by_role("textbox", name=re.compile(settings.EMAIL_FIELD_LABEL, re.IGNORECASE)),
            page.get_by_placeholder(re.compile(settings.EMAIL_FIELD_LABEL, re.IGNORECASE)),
            page.locator("input[type='email']"),
        ],
        settings.LOGIN_EMAIL,
        "email",
    )
    _fill_first(
        [
            page.get_by_label(settings.PASSWORD_FIELD_LABEL),
            page.get_by_role("textbox", name=re.compile(settings.PASSWORD_FIELD_LABEL, re.IGNORECASE)),
            page.get_by_placeholder(re.compile(settings.PASSWORD_FIELD_LABEL, re.IGNORECASE)),
            page.locator("input[type='password']"),
        ],
        settings.LOGIN_PASSWORD,
        "password",
    )

    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")

    # Wait for the URL to leave the login page.
    # Uses /login$ so intermediate redirect paths like /loginCallback don't
    # trigger a false "login failed" error.
    try:
        page.wait_for_url(
            lambda url: not re.search(r"/login/?$", url.rstrip("/"), re.IGNORECASE),
            timeout=10000,
        )
    except Exception:
        pass  # Handled by the explicit check below

    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")

    # Fail only if the final URL is still exactly the login endpoint
    if re.search(r"/login/?$", page.url.rstrip("/"), re.IGNORECASE):
        raise RuntimeError("Login failed: still on login page after submit")


# ── App Helper Library (auto-generated from recorded_flow.py) ────────
# Regenerated automatically whenever recorded_flow.py changes.
# The LLM calls these helpers — it never writes raw selectors.


def _app_navigate_to(page, section: str):
    """Navigate to a section by its link name. Known sections: Folders, Tag
Cloud, Workflows, Products, Analytics"""
    page.get_by_role("link", name=section).click()
    page.wait_for_load_state("networkidle")

def _app_open_filters_section(page):
    """Open/expand the 'Filters' section. Source: page.locator("#rc-tabs-0-tab-
filters div").filter(has_text=re.compile(r"^Filters$")).click()"""
    clicked = False
    for _role in ["tab", "link", "button"]:
        try:
            loc = page.get_by_role(_role, name=re.compile(r"^Filters$", re.IGNORECASE)).first
            if loc.is_visible(timeout=2000):
                loc.click()
                clicked = True
                break
        except Exception:
            pass
    if not clicked:
        try:
            page.get_by_text("Filters", exact=True).first.click()
            clicked = True
        except Exception:
            pass
    if not clicked:
        page.locator("#rc-tabs-0-tab-filters div").filter(has_text=re.compile(r"^Filters$", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")

def _app_open_tags_section(page):
    """Open/expand the 'Tags' section. Source:
page.locator("a").filter(has_text="Tags").click()"""
    clicked = False
    for _role in ["link", "tab", "button"]:
        try:
            loc = page.get_by_role(_role, name=re.compile(r"^Tags$", re.IGNORECASE)).first
            if loc.is_visible(timeout=2000):
                loc.click()
                clicked = True
                break
        except Exception:
            pass
    if not clicked:
        try:
            page.get_by_text("Tags", exact=True).first.click()
            clicked = True
        except Exception:
            pass
    if not clicked:
        page.locator("a").filter(has_text=re.compile(r"^Tags$", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")

def _app_open_filter_panel(page):
    """Open the filter panel and expand the default section. Calls the
individual filter helpers generated from the recording."""
    _app_open_filters_section(page)
    _app_open_tags_section(page)

def _app_search(page, query: str):
    """Type a search/filter query. Source selector: #rc_select_6"""
    page.locator("#rc_select_6").click()
    page.locator("#rc_select_6").fill(query)
    page.wait_for_load_state("networkidle")

def _app_apply_or_operator(page, nth: int = 0):
    """Click the OR operator button. nth=0 for first, nth=N for subsequent."""
    clicked = False
    if nth == 0:
        try:
            loc = page.get_by_role("button", name=re.compile(r"^OR$", re.IGNORECASE)).first
            if loc.is_visible(timeout=2000):
                loc.click()
                clicked = True
        except Exception:
            pass
        if not clicked:
            page.get_by_text("OR", exact=True).first.click()
    else:
        page.get_by_text("OR").nth(nth).click()
    page.wait_for_load_state("networkidle")

def _app_tag_locator(page, tag_name: str):
    """Return a locator for a tag item by name (count suffix optional)."""
    pattern = re.compile(rf"^{re.escape(tag_name)}(\d+)?$", re.IGNORECASE)
    loc = page.locator("a,div,span,li,button").filter(has_text=pattern).first
    try:
        if loc.is_visible(timeout=1000):
            return loc
    except Exception:
        pass
    return page.get_by_text(tag_name, exact=True).first

def _app_is_tag_selected(page, tag_name: str):
    """Return True if the tag appears selected/active."""
    loc = _app_tag_locator(page, tag_name)
    try:
        cls = (loc.get_attribute("class") or "").lower()
        if "selected" in cls or "active" in cls:
            return True
        if (loc.get_attribute("aria-selected") == "true" or loc.get_attribute("aria-pressed") == "true"):
            return True
    except Exception:
        pass
    return False

def _app_click_tag(page, tag_name: str):
    """Click a tag filter item by name only (count suffix is ignored). Tags
display as name+count e.g. 'toys59'. Sample names from recording: Delete
Asset, Vehicles, Lakshmi, Mr Cuddles, EN"""
    loc = _app_tag_locator(page, tag_name)
    try:
        loc.click()
    except Exception:
        try:
            page.get_by_text(re.compile(rf"^{re.escape(tag_name)}\d+$")).first.click()
        except Exception:
            page.get_by_text(tag_name, exact=True).first.click()
    page.wait_for_load_state("networkidle")

def _app_get_visible_tags(page):
    """Return list of tag names (without count) visible in the tag panel."""
    try:
        tags = []
        for tag in ["a", "div", "span", "li"]:
            elems = page.locator(tag).filter(
                has_text=re.compile(r"^\w[\w\s]+\d+$")
            ).all()
            for e in elems:
                t = re.sub(r"\d+$", "", e.inner_text(timeout=2000).strip()).strip()
                if t and t not in tags:
                    tags.append(t)
            if tags:
                break
        if not tags:
            sel = page.locator("*[aria-selected='true'], *[aria-pressed='true'], .selected, .active").all()
            for e in sel:
                t = (e.inner_text(timeout=2000) or "").strip()
                if t:
                    t = re.sub(r"\d+$", "", t).strip()
                    if t and t not in tags and len(t) <= 30:
                        tags.append(t)
        return tags
    except Exception:
        return []

def _app_get_result_count(page):
    """Read the total result count from a 'Total N items' label. Returns 0 if
not found."""
    try:
        text = page.get_by_text(
            re.compile(r"Total \d+ items")
        ).first.inner_text(timeout=5000)
        m = re.search(r"(\d+)", text)
        return int(m.group(1)) if m else 0
    except Exception:
        return 0

def _app_assert_result_count(page, expected: int = None, msg: str = '', expected_count: int = None):
    """Assert the total result count equals expected."""
    if expected is None and expected_count is not None:
        expected = expected_count
    actual = _app_get_result_count(page)
    assert actual == expected, (
        f"{msg or 'Result count'}: expected {expected}, got {actual}"
    )

def _app_open_asset(page, index: int = 0):
    """Click a thumbnail to open an asset. index=0 for the first."""
    page.get_by_role("img", name="thumb").nth(index).click()
    page.wait_for_load_state("networkidle")

def _app_click_asset_tab(page, tab_name: str):
    """Click an asset detail tab by name. Known tabs: References, Folders"""
    page.get_by_role("tab", name=tab_name).click()
    page.wait_for_load_state("networkidle")

def _app_clear_search(page):
    """Clear Search"""
    page.get_by_text("Clear Search").click()
    page.wait_for_load_state("networkidle")

# ── End App Helper Library ───────────────────────────────────────────

def _precondition(page):
    """
    Runs the configured STORY_PRECONDITIONS_JSON steps before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.STORY_PRECONDITIONS_JSON — change in .env, no code edits.
    """
    # Click Filters
    page.locator("#rc-tabs-0-tab-filters div").filter(has_text=re.compile(r"^Filters$")).first.click()
    page.wait_for_load_state("networkidle")
    # Expand Tags
    page.locator("a").filter(has_text="Tags").first.click()
    page.wait_for_load_state("networkidle")


def test_no_filters_applied_initially(page):

    try:
        _login(page)
        _precondition(page)

        # Verify that the Advanced Filter section is displayed with no filters applied
        filter_panel = page.locator("[id*='tab-filters']")
        expect(filter_panel).to_be_visible()

        # Select the OR operator to add a new filter
        _app_apply_or_operator(page)

        # Verify that the filter panel reloads and displays available filter options
        page.wait_for_load_state("networkidle")
        available_tags = _app_get_visible_tags(page)
        assert len(available_tags) > 0, "No filter options available after selecting OR operator"

    except Exception:
        page.screenshot(path="failure_test_no_filters_applied_initially.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(10000)
            page = _ctx.new_page()
            _page = page
            page.on('framenavigated', lambda frame: print(f"NAVIGATED: {frame.url}", flush=True) if frame == page.main_frame else None)
            page.on('console', lambda msg: print(f"CONSOLE: {msg.type} {msg.text}", flush=True))
            page.on('pageerror', lambda err: print(f"PAGEERROR: {err}", flush=True))
            print(f"START_URL: {page.url}", flush=True)
            try:
                test_no_filters_applied_initially(page)
            except Exception:
                _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/no_filters_applied_initially_20260305_140026.png")
                raise
            finally:
                try: _ctx.close()
                except Exception: pass
                try: _browser.close()
                except Exception: pass
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _exit = 1
    sys.exit(_exit)
