import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: BUSINESS_RULES - Top 20 tags concept is respected
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_top_20_tags_displayed_post_filter(page):

    try:
        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Select a tag that results in more than 20 additional tags being applicable
        # Assuming there's a dropdown or a list to select a tag from
        page.get_by_role("combobox").select_option({"label": "Specific Tag"})
        page.wait_for_load_state("networkidle")

        # After selecting a tag, the system should filter and display additional tags
        # Assuming there's a container that holds the tags and each tag has a specific role or identifier
        tags = page.locator("[data-testid='additional-tags-container'] [role='listitem']")

        # Count the number of tags displayed after filtering
        count_of_tags_displayed = tags.count()

        # Assert that only the top 20 tags are displayed
        assert count_of_tags_displayed == 20, f"Expected 20 tags to be displayed, but found {count_of_tags_displayed}"

        # Optionally, verify the sorting order based on the count of associated assets
        # This step assumes each tag has an associated count element that can be read
        previous_count = float('inf')
        for i in range(count_of_tags_displayed):
            current_count = int(tags.nth(i).get_by_role("status").text_content())
            assert current_count <= previous_count, "Tags are not sorted in descending order based on the count of associated assets"
            previous_count = current_count

    except Exception:
        page.screenshot(path="failure_test_top_20_tags_displayed_post_filter.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_top_20_tags_displayed_post_filter(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/top_20_tags_displayed_post_filter_20260217_124626.png")
        _exit = 1
    sys.exit(_exit)
