import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ASYNC_TIMING - UI updates seamlessly after loading additional tags
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_seamless_ui_update_post_loading(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Select a tag by clicking on it. Assuming tags are buttons for this example.
        tag_to_select = "Example Tag"  # This should be replaced with a real tag value relevant to the application.
        page.get_by_role("button", name=tag_to_select).click()

        # Wait for the additional tags to load after selecting a tag.
        page.wait_for_load_state("networkidle")

        # Verify that the UI updates to display the additional tags without any noticeable delays or glitches.
        # This assumes the additional tags have a specific role or label that can be checked.
        # For demonstration, we'll assume they are listed items within a container with a role of 'list'.
        additional_tags_container = page.get_by_role("list")
        # Ensure the container for additional tags is visible, indicating UI has updated.
        expect(additional_tags_container).to_be_visible()

        # Further verification could include checking the count of tags is greater than 1 to ensure additional tags were loaded.
        additional_tags = additional_tags_container.locator("li")  # Assuming each tag is an item in the list.
        assert additional_tags.count() > 1, "Expected more than one tag to be loaded and displayed."

        # Optionally, verify one of the newly loaded tags by its visible text.
        # This step assumes a specific tag that should appear as a result of the selection.
        expected_new_tag = "Related Tag"  # This should be replaced with an expected tag relevant to the application.
        expect(page.get_by_text(expected_new_tag, exact=False)).to_be_visible()

    except Exception:
        page.screenshot(path="failure_test_seamless_ui_update_post_loading.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_seamless_ui_update_post_loading(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/seamless_ui_update_post_loading_20260217_131507.png")
        _exit = 1
    sys.exit(_exit)
