import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ASYNC_TIMING - Applying OR operator with slow network
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_or_operator_slow_network(page):

    try:
        # Simulate slow network conditions for API requests
        page.route("**/api/**", lambda r: r.abort("failed"))

        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)

        # Apply a filter, assuming filters are accessible via a generic control like a dropdown
        page.get_by_role("combobox", name="Filters").click()
        page.get_by_text("Apply Filter", exact=False).click()
        page.wait_for_load_state("networkidle")

        # Select the OR operator, assuming it's a button or similar control
        page.get_by_role("button", name="OR").click()

        # Wait for the filter panel to reload and verify the correct state is preserved
        page.wait_for_load_state("networkidle")

        # Assuming the filter panel has a state indicator we can check
        filter_state = page.get_by_text("Filter State: OR", exact=False)
        expect(filter_state).to_be_visible()

        # Additional assertion to ensure the system handled the slow network condition gracefully
        # This could be checking for a loading spinner disappearance or similar indication
        loading_indicator = page.locator("[data-testid='loading-spinner']")
        expect(loading_indicator).not_to_be_visible()

    except Exception:
        page.screenshot(path="failure_test_or_operator_slow_network.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_or_operator_slow_network(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/or_operator_slow_network_20260217_134028.png")
        _exit = 1
    sys.exit(_exit)
