import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: UI_UX_CONSISTENCY - Newly added tags match existing UI elements
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_ui_consistency_for_new_tags(page):

    try:
        # Navigate to the base URL and wait for the page to be fully loaded
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Wait for the filter panel to be fully loaded
        page.wait_for_load_state("networkidle")

        # Capture the style of existing tags for comparison
        existing_tags = page.locator("[data-testid='filter-tag']")
        first_tag_style = existing_tags.first.evaluate("e => getComputedStyle(e).cssText")

        # Simulate the addition of a new tag to the filter panel
        # This step is highly dependent on the application's functionality.
        # It might involve clicking a "New Tag" button, submitting a form, or triggering a mock API response.
        # For demonstration, let's assume there's a button to add a new tag.
        page.click("[data-testid='add-new-tag-btn']")
        page.wait_for_load_state("networkidle")

        # Locate the newly added tag
        new_tag = page.locator("[data-testid='filter-tag']").last()

        # Compare the style of the newly added tag with the first tag
        new_tag_style = new_tag.evaluate("e => getComputedStyle(e).cssText")
        assert new_tag_style == first_tag_style, "New tag style does not match existing tags"

        # Ensure the new tag is visible and matches the expected UI elements
        expect(new_tag).to_be_visible()
        expect(existing_tags).to_have_count(existing_tags.count() + 1, "New tag was not added to the UI")

    except Exception:
        page.screenshot(path="failure_test_ui_consistency_for_new_tags.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_ui_consistency_for_new_tags(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/ui_consistency_for_new_tags_20260217_101338.png")
        _exit = 1
    sys.exit(_exit)
