import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: SEQUENTIAL_REFINEMENT - User refines search by selecting an auto-populated tag
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_refine_search_with_auto_populated_tag(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Assuming the search field and tags are part of a form or identifiable section
        # Select Tag A from the available options
        page.click("[data-testid='tag-selector']")
        page.click("[data-testid='tag-A']")
        page.wait_for_load_state("networkidle")

        # Wait for the additional tags to auto-populate based on Tag A selection
        # This might need a specific wait condition if the tags are loaded dynamically (not covered by networkidle)
        page.wait_for_selector("[data-testid='auto-populated-tag']", state="visible")

        # Select an auto-populated Tag B
        page.click("[data-testid='auto-populated-tag-B']")
        page.wait_for_load_state("networkidle")

        # Submit the refined search
        page.click("[data-testid='submit-btn']")
        page.wait_for_load_state("networkidle")

        # Verify the URL or page state to confirm both tags are applied
        # This is a placeholder for actual verification logic, which might involve checking the URL, page content, or API calls
        assert "TagA" in page.url() and "TagB" in page.url(), "URL does not contain both Tag A and Tag B parameters"

        # Alternatively, verify the search results are as expected
        # This could involve checking the number of results, specific items present, etc.
        # Example assertion on the number of results shown
        results = page.locator("[data-testid='search-result']")
        count = results.count()
        assert count > 0, "No results found with both Tag A and Tag B"

    except Exception:
        page.screenshot(path="failure_test_refine_search_with_auto_populated_tag.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_refine_search_with_auto_populated_tag(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/refine_search_with_auto_populated_tag_20260217_124618.png")
        _exit = 1
    sys.exit(_exit)
