import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

def _dump_debug():
    global _page
    if not _page:
        return
    try:
        print(f"DEBUG_URL: {_page.url}")
    except Exception:
        pass
    try:
        print(f"DEBUG_TITLE: {_page.title()}")
    except Exception:
        pass

"""
Test: HAPPY_PATH - Select a tag and see additional tags auto-populate
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    # Step 1: Click Filter, Expand Tags
    page.get_by_text("Filters", exact=False).click()
    page.wait_for_load_state("networkidle")


def test_auto_populate_additional_tags_after_initial_selection(page):

    try:
        _login(page)
        _precondition(page)  # This will click Filter and expand Tags as per the pre-steps
        page.wait_for_load_state("networkidle")

        # Assuming 'Tag A' is visible after expanding the Tags section
        # and can be selected by text. Replace 'Tag A' with the actual text if needed.
        page.locator("text=Tag A").click()
        page.wait_for_load_state("networkidle")

        # Verify that assets related to 'Tag A' are displayed
        # This is a generic check to ensure that some assets are indeed displayed
        # after selecting a tag. Replace '[data-testid="asset-item"]' with the actual
        # testid or a more specific selector that matches your application.
        assert page.locator("[data-testid='asset-item']").count() > 0, "No assets displayed after selecting Tag A"

        # Verify additional tags related to the displayed assets auto-populate in the filter panel
        # This is a generic check to ensure that at least one additional tag is displayed
        # after selecting 'Tag A'. Replace 'Additional Tag' with actual text if needed.
        # This assumes that the additional tags are within a container that can be identified.
        # Replace '[data-testid="additional-tags-container"]' with the actual testid or
        # a more specific selector that matches your application.
        assert page.locator("[data-testid='additional-tags-container'] >> text=Additional Tag").count() > 0, "No additional tags displayed after selecting Tag A"

    except Exception:
        page.screenshot(path="failure_test_auto_populate_additional_tags_after_initial_selection.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            page.on('framenavigated', lambda frame: print(f"NAVIGATED: {frame.url}") if frame == page.main_frame else None)
            page.on('console', lambda msg: print(f"CONSOLE: {msg.type} {msg.text}"))
            page.on('pageerror', lambda err: print(f"PAGEERROR: {err}"))
            try:
                test_auto_populate_additional_tags_after_initial_selection(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _dump_debug()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/auto_populate_additional_tags_after_init_20260219_104814.png")
        _exit = 1
    sys.exit(_exit)
