import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: CLEAR_RESET_ALL - Using global clear filters functionality
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_clear_filters_returns_to_baseline(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Log in to the application
        _login(page)

        # Select a tag to filter results, assuming a generic locator for demonstration
        page.locator("[data-testid='tag-selector']").click()
        page.locator("text=Tag1").click()

        # Wait for auto-populated tags to appear
        page.wait_for_load_state("networkidle")

        # Use the global 'clear filters' option
        page.locator("text=Clear filters").click()

        # Wait for the action to complete and the filter panel to return to its baseline state
        page.wait_for_load_state("networkidle")

        # Assert that no tags are selected by checking the absence of selected tag indicators
        # This is a generic assertion, assuming tags have a 'selected' class when active
        selected_tags = page.locator(".tag.selected").count()
        assert selected_tags == 0, f"Expected no selected tags, found {selected_tags}"

        # Optionally, verify the URL or other indicators have returned to their baseline state
        # This step depends on the application's behavior and might need adjustment
        assert "filters=none" in page.url or page.locator("text=No filters applied").is_visible(), "Filter panel did not return to baseline state"

    except Exception:
        page.screenshot(path="failure_test_clear_filters_returns_to_baseline.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_clear_filters_returns_to_baseline(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/clear_filters_returns_to_baseline_20260217_124641.png")
        _exit = 1
    sys.exit(_exit)
