import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ERROR_FAILURE - Handle filter reload failure gracefully
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_filter_reload_failure_handling(page):

    try:
        # Navigate to the base URL and wait for the page to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Simulate a network failure on filter reload request
        page.route("**/api/filters/**", lambda r: r.abort("failed"))

        # Trigger the filter reload, assuming a UI element to do so
        page.locator("[data-testid='filter-reload-btn']").click()

        # Wait for the error message to appear
        page.wait_for_selector("[data-testid='error-message']", state="visible")

        # Assert that the error message is displayed and contains the correct text
        error_message = page.locator("[data-testid='error-message']")
        expect(error_message).to_have_text("Error loading filters", exact=False)

        # Assert that the user's filter selections are preserved
        # Assuming there's a way to check a specific filter's state, e.g., by its label
        filter_checkbox = page.locator("[data-testid='filter-checkbox'][aria-checked='true']")
        assert filter_checkbox.count() > 0, "Expected at least one filter to remain selected"

    except Exception:
        page.screenshot(path="failure_test_filter_reload_failure_handling.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_filter_reload_failure_handling(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/filter_reload_failure_handling_20260217_124705.png")
        _exit = 1
    sys.exit(_exit)
