import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

def _dump_debug():
    global _page
    if not _page:
        return
    try:
        _page.wait_for_load_state('domcontentloaded', timeout=2000)
    except Exception:
        pass
    try:
        print(f"DEBUG_URL: {_page.url}")
    except Exception:
        pass

"""
Test: BUSINESS_RULES - Display top 20 tags
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


# ── App Helper Library (auto-generated from recorded_flow.py) ────────
# Regenerated automatically whenever recorded_flow.py changes.
# The LLM calls these helpers — it never writes raw selectors.


# ── End App Helper Library ───────────────────────────────────────────

def _precondition(page):
    """
    Runs the configured STORY_PRECONDITIONS_JSON steps before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.STORY_PRECONDITIONS_JSON — change in .env, no code edits.
    """
    # Click Filters
    page.locator("#rc-tabs-0-tab-filters div").filter(has_text=re.compile(r"^Filters$")).first.click()
    page.wait_for_load_state("networkidle")
    # Click Tags
    page.locator("a").filter(has_text="Tags").first.click()
    page.wait_for_load_state("networkidle")


def test_display_top_20_tags_only(page):

    try:
        _login(page)
        _precondition(page)

        # Wait for the page to be fully loaded
        page.wait_for_load_state("networkidle")

        # Dynamically select a tag associated with assets that have more than 20 unique tags
        # Assuming there's a dropdown or list to select from, and we select the first one
        tag_selector = page.locator("[data-testid='tag-selector']")
        tag_selector.click()
        page.wait_for_load_state("networkidle")

        # Select the first tag in the list
        first_tag = tag_selector.locator("li").first
        first_tag_text = first_tag.inner_text()
        first_tag.click()
        page.wait_for_load_state("networkidle")

        # Verify that only the top 20 tags are displayed
        displayed_tags = page.locator("[data-testid='tag-list'] li")
        tag_count = displayed_tags.count()
        assert tag_count == 20, f"Expected 20 tags, but found {tag_count}"

        # Verify that the selected tag is among the displayed tags
        expect(displayed_tags).to_contain_text(first_tag_text)

    except Exception:
        page.screenshot(path="failure_test_display_top_20_tags_only.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(10000)
            page = _ctx.new_page()
            _page = page
            page.on('framenavigated', lambda frame: print(f"NAVIGATED: {frame.url}", flush=True) if frame == page.main_frame else None)
            page.on('console', lambda msg: print(f"CONSOLE: {msg.type} {msg.text}", flush=True))
            page.on('pageerror', lambda err: print(f"PAGEERROR: {err}", flush=True))
            print(f"START_URL: {page.url}", flush=True)
            try:
                test_display_top_20_tags_only(page)
            except Exception:
                _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/display_top_20_tags_only_20260223_133712.png")
                raise
            finally:
                try: _ctx.close()
                except Exception: pass
                try: _browser.close()
                except Exception: pass
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _exit = 1
    sys.exit(_exit)
