import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: UI_UX_CONSISTENCY - UI consistency after applying OR operator
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_ui_consistency_after_applying_or(page):

    try:
        # Navigate to the base URL
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)
        page.wait_for_load_state("networkidle")

        # Navigate to the page with the filter functionality
        # Assuming 'Filters' is the text on the navigation menu or button to reach the filters page
        page.get_by_text("Filters", exact=True).click()
        page.wait_for_load_state("networkidle")

        # Apply a filter using a generic placeholder, assuming a text input field for filters
        # This is a placeholder for the actual filter input, which would depend on the application's UI
        filter_input = page.get_by_placeholder("Enter keyword")
        filter_input.fill("example")
        page.wait_for_load_state("networkidle")

        # Select the OR operator, assuming it's a button or a selectable UI element
        # This is a placeholder for the actual action to select the OR operator
        page.get_by_text("OR", exact=True).click()
        page.wait_for_load_state("networkidle")

        # Observe the UI for consistency
        # This would typically involve checking that the filter input is still present
        # and that no UI elements have been reset or flickered
        # Here, we assert the filter input still contains the same value
        assert filter_input.input_value() == "example", "Filter input was reset or lost after applying OR operator"

        # Additionally, check for any visual flickers or resets by ensuring the page URL hasn't changed unexpectedly
        assert page.url == settings.BASE_URL + "/filters", "Unexpected page navigation detected"

        # Optionally, more sophisticated checks could involve taking screenshots before and after applying the OR operator
        # and comparing them for any unexpected changes, but this is beyond the scope of this simple test

    except Exception:
        page.screenshot(path="failure_test_ui_consistency_after_applying_or.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_ui_consistency_after_applying_or(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/ui_consistency_after_applying_or_20260218_072609.png")
        _exit = 1
    sys.exit(_exit)
