import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: PERFORMANCE_SCALE - Applying OR operator with large data sets
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_or_operator_large_data_sets(page):

    try:
        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Navigate to the page with the large data set
        page.goto(f"{settings.BASE_URL}/large-data-set")
        page.wait_for_load_state("networkidle")

        # Apply the first filter on the large data set
        page.locator("[data-testid='filter-input']").fill("Filter Value 1")
        page.locator("[data-testid='apply-filter-btn']").click()
        page.wait_for_load_state("networkidle")

        # Select the OR operator for the next filter application
        page.locator("[data-testid='or-operator-btn']").click()
        page.wait_for_load_state("networkidle")

        # Apply the second filter using the OR operator
        page.locator("[data-testid='filter-input']").fill("Filter Value 2")
        page.locator("[data-testid='apply-filter-btn']").click()

        # Start timing for performance measurement
        start_time = time.time()

        # Wait for the filter panel to reload
        page.wait_for_load_state("networkidle")

        # End timing for performance measurement
        end_time = time.time()

        # Check that the filter panel has reloaded by verifying a UI element that should be present after reload
        assert page.locator("[data-testid='filter-panel']").is_visible(), "Filter panel did not reload"

        # Verify the performance is not significantly degraded
        assert (end_time - start_time) < 5, f"Filter panel reload took {end_time - start_time:.2f}s, indicating potential performance degradation"

    except Exception:
        page.screenshot(path="failure_test_or_operator_large_data_sets.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_or_operator_large_data_sets(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/or_operator_large_data_sets_20260218_073115.png")
        _exit = 1
    sys.exit(_exit)
