import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: ASYNC_TIMING - Verify tag population post async load
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    pass  # No precondition steps configured


def test_verify_tag_population_post_async_load(page):

    try:
        _login(page)
        _precondition(page)

        # Simulate slow network conditions
        page.route("**/*", lambda route: route.continue_(delay=5000))

        # Select a tag to filter the results
        page.locator("[data-testid='tag-selector']").click()
        page.locator("text=Tag Name").click()  # Replace 'Tag Name' with the actual tag name to be tested

        # Wait for the results to load under slow network conditions
        page.wait_for_load_state("networkidle")

        # Verify that the tags associated with the returned assets are populated without delay
        # This assumes that the tags are displayed in a container with a specific test ID or similar identifiable attribute
        tags_displayed = page.locator("[data-testid='tags-display-container']").locator("text=Tag Name")  # Replace 'Tag Name' as needed
        count = tags_displayed.count()
        assert count > 0, "Expected at least one tag to be displayed, but found none."

        # Additional check to ensure no duplicate tags are displayed
        seen_tags = set()
        for i in range(count):
            tag_text = tags_displayed.nth(i).text_content()
            assert tag_text not in seen_tags, f"Duplicate tag found: {tag_text}"
            seen_tags.add(tag_text)

    except Exception:
        page.screenshot(path="failure_test_verify_tag_population_post_async_load.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_verify_tag_population_post_async_load(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/verify_tag_population_post_async_load_20260218_120651.png")
        _exit = 1
    sys.exit(_exit)
