import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: BUSINESS_RULES - Verify top 20 highest count tags are displayed without omission
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    # Step 1: Click Filter, Expand Tags
    page.get_by_role("button", name=re.compile(r"Filter, Expand Tags", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")


def test_verify_top_20_tags_displayed(page):

    try:
        _login(page)
        _precondition(page)
        # Step 1: Filter results by a tag that leads to a large number of additional tags being applicable.
        # Since the specific tag to filter by isn't provided, we'll simulate selecting a generic tag.
        # This assumes there's a way to select a tag from the UI, e.g., clicking on a tag element.
        page.locator("[data-testid='tag-selector']").click()  # Simulating clicking on a tag selector
        page.wait_for_load_state("networkidle")

        # After filtering by a tag, we expect only the top 20 tags to be displayed.
        # This checks the count of tag elements in the filter panel.
        tags_displayed = page.locator("[data-testid='tag-in-filter-panel']")
        count = tags_displayed.count()

        # Assert that no more than 20 tags are displayed.
        assert count <= 20, f"Expected up to 20 tags, found {count}"

        # Optionally, to further validate the correctness of the displayed tags,
        # one could fetch the tags' text content and perform additional checks,
        # such as verifying specific expected tags are present.
        # This step is omitted here due to the lack of specific tag names or IDs to check against.
    except Exception:
        page.screenshot(path="failure_test_verify_top_20_tags_displayed.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_verify_top_20_tags_displayed(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/verify_top_20_tags_displayed_20260218_154516.png")
        _exit = 1
    sys.exit(_exit)
