import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: BUSINESS_RULES - Updated filter options based on metadata and selections
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_updated_filter_options_post_reload(page):

    try:
        # Navigate to the base URL
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Ensure login is successful
        _login(page)
        page.wait_for_load_state("networkidle")

        # Apply an initial filter (generic action)
        page.locator("[data-testid='filter-option']").first.click()
        page.locator("[data-testid='or-operator']").click()
        page.wait_for_load_state("networkidle")

        # Trigger the reload to update filter options
        page.locator("[data-testid='apply-filters']").click()
        page.wait_for_load_state("networkidle")

        # Assert that the URL or page state indicates that filters have been applied
        assert "filters=applied" in page.url, "Filters not applied as expected."

        # Verify that updated filter options are displayed
        updated_filters_count = page.locator("[data-testid='updated-filter-option']").count()
        assert updated_filters_count > 0, "Updated filter options not displayed."

        # Further validation to ensure the filter options are relevant could be done here,
        # for example, by checking the text or properties of the updated filter options
        # to ensure they match expected criteria based on the previously applied filters and metadata.
        # This step is left generic due to the wide variety of possible implementations.

    except Exception:
        page.screenshot(path="failure_test_updated_filter_options_post_reload.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_updated_filter_options_post_reload(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/updated_filter_options_post_reload_20260217_124709.png")
        _exit = 1
    sys.exit(_exit)
