import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: UI_UX_CONSISTENCY - Newly added tags match existing filter UI style
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    # Step 1: Login to the application
    page.wait_for_load_state("networkidle")
    page.wait_for_load_state("networkidle")
    # Step 2: Click the Filter button in the left side menu to open the filter panel
    page.get_by_role("button", name=re.compile(r"the Filter button in the left side menu ", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")
    # Step 3: Expand the Tags section
    page.get_by_text(re.compile(r"the Tags section", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")


def test_newly_added_tags_ui_consistency(page):

    try:
        _login(page)
        _precondition(page)

        # Select Tag A to trigger the population of additional tags
        page.locator("text=Tag A").click()
        page.wait_for_load_state("networkidle")

        # Verify that additional tags have appeared
        additional_tags = page.locator("css=[data-testid='additional-tags']")
        assert additional_tags.count() > 0, "No additional tags were populated."

        # Check for UI consistency between the newly added tags and existing tag filters
        existing_tag_filters_style = page.locator("css=[data-testid='existing-tag-filters']").get_attribute("class")
        additional_tags_style = additional_tags.get_attribute("class")
        assert existing_tag_filters_style == additional_tags_style, "UI styles of newly added tags and existing tag filters do not match."

    except Exception:
        page.screenshot(path="failure_test_newly_added_tags_ui_consistency.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_newly_added_tags_ui_consistency(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/newly_added_tags_ui_consistency_20260218_132520.png")
        _exit = 1
    sys.exit(_exit)
