import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

def _dump_debug():
    global _page
    if not _page:
        return
    try:
        _page.wait_for_load_state('domcontentloaded', timeout=2000)
    except Exception:
        pass
    try:
        print(f"DEBUG_URL: {_page.url}")
    except Exception:
        pass

"""
Test: BUSINESS_RULES - Updated filter options based on metadata and selections
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


# ── App Helper Library (auto-generated from recorded_flow.py) ────────
# Regenerated automatically whenever recorded_flow.py changes.
# The LLM calls these helpers — it never writes raw selectors.


# ── End App Helper Library ───────────────────────────────────────────

def _precondition(page):
    """
    Runs the configured STORY_PRECONDITIONS_JSON steps before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.STORY_PRECONDITIONS_JSON — change in .env, no code edits.
    """
    # Click Filters
    page.locator("#rc-tabs-0-tab-filters div").filter(has_text=re.compile(r"^Filters$")).first.click()
    page.wait_for_load_state("networkidle")
    # Click Tags
    page.locator("a").filter(has_text="Tags").first.click()
    page.wait_for_load_state("networkidle")
    # Click tag toys
    _app_click_tag(page, "toys")
    page.wait_for_load_state("networkidle")
    # Click OR
    _app_apply_or_operator(page)
    page.wait_for_load_state("networkidle")


def test_updated_filter_options_post_or_operator(page):

    try:
        _login(page)
        _precondition(page)

        # Step 1: Apply a filter, select the OR operator, and observe the updated filter options.
        page.get_by_role("button", name="Filters").click()
        page.wait_for_load_state("networkidle")

        # Assuming the filter options are displayed in a dropdown or similar UI component
        filter_dropdown = page.locator("[data-testid='filter-dropdown']")
        filter_dropdown.click()
        page.wait_for_load_state("networkidle")

        # Select a filter option, for example, "Category"
        page.get_by_text("Category").click()
        page.wait_for_load_state("networkidle")

        # Select the OR operator
        page.get_by_text("OR").click()
        page.wait_for_load_state("networkidle")

        # Verify that the filter options are updated and relevant
        updated_filter_options = page.locator("[data-testid='updated-filter-options']")
        expect(updated_filter_options).to_be_visible()
        expect(updated_filter_options).to_contain_text("Relevant Option 1")
        expect(updated_filter_options).to_contain_text("Relevant Option 2")

    except Exception:
        page.screenshot(path="failure_test_updated_filter_options_post_or_operator.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(10000)
            page = _ctx.new_page()
            _page = page
            page.on('framenavigated', lambda frame: print(f"NAVIGATED: {frame.url}", flush=True) if frame == page.main_frame else None)
            page.on('console', lambda msg: print(f"CONSOLE: {msg.type} {msg.text}", flush=True))
            page.on('pageerror', lambda err: print(f"PAGEERROR: {err}", flush=True))
            print(f"START_URL: {page.url}", flush=True)
            try:
                test_updated_filter_options_post_or_operator(page)
            except Exception:
                _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/updated_filter_options_post_or_operator_20260223_133940.png")
                raise
            finally:
                try: _ctx.close()
                except Exception: pass
                try: _browser.close()
                except Exception: pass
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _exit = 1
    sys.exit(_exit)
