import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: PERFORMANCE_SCALE - Large data sets handling
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_handling_large_data_sets_with_auto_tags(page):

    try:
        # Navigate to the base URL and wait for the page to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Navigate to the page where tags can be selected (assuming a generic URL path for demonstration)
        page.goto(f"{settings.BASE_URL}/data-sets")
        page.wait_for_load_state("networkidle")

        # Select a tag from a large data set
        # Assuming there's a dropdown or a list to select tags, and the tags have a common selector
        page.locator("[data-testid='tag-selector']").click()
        page.locator("[data-testid='tag-option']", has_text="SpecificTag").click()

        # Wait for the filtering process to complete and additional tags to auto-populate
        start_time = time.time()
        page.wait_for_load_state("networkidle")
        end_time = time.time()

        # Check if the additional tags related to the filtered results are displayed
        # Assuming additional tags are populated in a container with a specific test ID
        additional_tags = page.locator("[data-testid='additional-tags-container']")
        expect(additional_tags).to_have_count(1)  # Expecting at least one container for additional tags

        # Assert that the auto-population of additional tags did not take more than 5 seconds
        # This checks the efficiency of handling large data sets
        assert (end_time - start_time) < 5, f"Auto-populating additional tags took {end_time - start_time:.2f}s, which is too long"

        # Optionally, verify some of the auto-populated tags to ensure they are relevant to the selected tag
        # This step assumes tags have text content that can be verified
        assert additional_tags.locator("text='RelatedTag1'").count() > 0, "Expected auto-populated tag 'RelatedTag1' is missing"
        assert additional_tags.locator("text='RelatedTag2'").count() > 0, "Expected auto-populated tag 'RelatedTag2' is missing"

    except Exception:
        page.screenshot(path="failure_test_handling_large_data_sets_with_auto_tags.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_handling_large_data_sets_with_auto_tags(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/handling_large_data_sets_with_auto_tags_20260217_124644.png")
        _exit = 1
    sys.exit(_exit)
