import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: HAPPY_PATH - User selects a tag and additional tags auto-populate
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_auto_populate_additional_tags_after_selection(page):

    try:
        # Navigate to the base URL
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)
        page.wait_for_load_state("networkidle")

        # Step 1: Select Tag A from the filter panel
        page.locator("[data-testid='tag-filter-panel']").locator("text=Tag A").click()
        page.wait_for_load_state("networkidle")

        # Assert that the results are filtered by Tag A
        filtered_results = page.locator("[data-testid='filtered-results']")
        assert filtered_results.count() > 0, "No results found after selecting Tag A"

        # Step 2: Wait for the filtered results to finish loading and check for additional tags
        page.wait_for_load_state("networkidle")
        additional_tags = page.locator("[data-testid='additional-tags']")
        assert additional_tags.count() > 0, "No additional tags found after filtering results"

        # Verify that additional tags are related to the displayed assets
        # This is a simplified check assuming there's a method to validate the relation
        for tag in additional_tags.all_text_contents():
            assert "Related" in tag, f"Tag {tag} is not related to the filtered assets"

    except Exception:
        page.screenshot(path="failure_test_auto_populate_additional_tags_after_selection.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_auto_populate_additional_tags_after_selection(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/auto_populate_additional_tags_after_sele_20260217_124614.png")
        _exit = 1
    sys.exit(_exit)
