import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: SEQUENTIAL_REFINEMENT - Sequentially refine search results
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    pass  # No precondition steps configured


def test_sequential_refinement_with_new_tags(page):

    try:
        _login(page)
        _precondition(page)

        # Step 1: Select an initial tag
        initial_tag = page.locator("[data-testid='tag']", first=True)
        initial_tag.click()
        page.wait_for_load_state("networkidle")

        # Verify initial tag selection triggers search results update
        initial_results_count = page.locator("[data-testid='search-result']").count()
        assert initial_results_count > 0, "Initial tag selection did not update search results."

        # Step 2: Wait for new tags to appear based on the initial search
        page.wait_for_selector("[data-testid='new-tag']")
        new_tag = page.locator("[data-testid='new-tag']", first=True)
        new_tag.click()
        page.wait_for_load_state("networkidle")

        # Verify new tag selection further refines search results
        refined_results_count = page.locator("[data-testid='search-result']").count()
        assert refined_results_count > 0, "New tag selection did not refine search results."
        assert refined_results_count < initial_results_count, "Refined results are not fewer than initial results."

    except Exception:
        page.screenshot(path="failure_test_sequential_refinement_with_new_tags.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_sequential_refinement_with_new_tags(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/sequential_refinement_with_new_tags_20260218_120647.png")
        _exit = 1
    sys.exit(_exit)
