import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: REMOVAL_DESELECTION - Deselecting a user-selected tag
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_deselecting_user_selected_tag(page):

    try:
        # Navigate to the base URL and wait for it to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)

        # Select Tag A by clicking on it. Assuming Tag A has a unique data-testid or text.
        tagA_locator = page.locator("[data-testid='tag-A']")
        tagA_locator.click()

        # Wait for the network to idle after selecting Tag A, which might load additional tags or content
        page.wait_for_load_state("networkidle")

        # Assert that Tag A is selected. This could be checking for a class change, aria-selected attribute, etc.
        assert tagA_locator.get_attribute("aria-selected") == "true", "Tag A should be selected"

        # Deselect Tag A by clicking on it again
        tagA_locator.click()

        # Wait for the network to idle after deselecting Tag A, as it might update the list of displayed tags or content
        page.wait_for_load_state("networkidle")

        # Assert that Tag A is deselected. This could be checking for a class change, aria-selected attribute, etc.
        assert tagA_locator.get_attribute("aria-selected") == "false", "Tag A should be deselected"

        # Assert the filter panel updates to remove the refinement. This might involve checking the absence of a specific element or text.
        assert page.locator("[data-testid='filter-panel']").locator("text=Tag A").count() == 0, "Filter panel should not contain Tag A after deselection"

        # Optionally, assert the list of displayed additional tags is updated. This step depends on the application's behavior and might require specific checks.
        # Example: Asserting the presence of a new tag or the absence of an old one.
        # This is a placeholder for such an assertion, adjust according to the actual application behavior.
        assert page.locator("[data-testid='additional-tags']").locator("text=New Tag").count() > 0, "Additional tags should be updated"

    except Exception:
        page.screenshot(path="failure_test_deselecting_user_selected_tag.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_deselecting_user_selected_tag(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/deselecting_user_selected_tag_20260217_124637.png")
        _exit = 1
    sys.exit(_exit)
