import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: REGRESSION - Verify unrelated features function post-reload
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_unrelated_features_functionality_post_reload(page):

    try:
        # Navigate to the base URL and wait for the page to load completely
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Apply filters using the OR operator (generic action, assuming filters are accessible)
        page.locator("[data-testid='filter-input']").fill("filter1 OR filter2")
        page.locator("[data-testid='apply-filter-btn']").click()
        page.wait_for_load_state("networkidle")

        # Reload the filters (assuming there's a button or link to reload filters)
        page.locator("[data-testid='reload-filters-btn']").click()
        page.wait_for_load_state("networkidle")

        # Use an unrelated feature to verify functionality post-reload
        # This could be anything from creating a new entry, searching, or navigating to a different section
        # For this example, let's assume we're verifying the search functionality
        page.locator("[data-testid='search-input']").fill("test search")
        page.locator("[data-testid='search-btn']").click()
        page.wait_for_load_state("networkidle")

        # Verify the unrelated feature works as expected
        # This could be checking for the presence of search results, for example
        search_results = page.locator("[data-testid='search-result']")
        assert search_results.count() > 0, "Expected search results to be present"

    except Exception:
        page.screenshot(path="failure_test_unrelated_features_functionality_post_reload.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_unrelated_features_functionality_post_reload(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/unrelated_features_functionality_post_re_20260217_124713.png")
        _exit = 1
    sys.exit(_exit)
