import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: UI_UX_CONSISTENCY - Newly added tags match existing filter UI elements
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    # Step 1: Click Filter, Expand Tags
    page.get_by_role("button", name=re.compile(r"Filter, Expand Tags", re.IGNORECASE)).first.click()
    page.wait_for_load_state("networkidle")


def test_new_tags_match_existing_ui_elements(page):

    try:
        _login(page)
        _precondition(page)
        page.wait_for_load_state("networkidle")

        # Assuming tags are represented as chips in a container with a specific role or data-testid
        existing_tags = page.locator("[data-testid='tag-chip']")
        initial_tag_count = existing_tags.count()

        # Triggering the auto-population of new tags, assuming this is done through an action like clicking a button
        # For this example, let's assume there's a "Refresh Tags" button. This is a placeholder for the actual trigger action.
        page.locator("[data-testid='refresh-tags-btn']").click()
        page.wait_for_load_state("networkidle")

        # Re-count the tags after the new ones have been auto-populated
        updated_tag_count = page.locator("[data-testid='tag-chip']").count()

        # Verify that new tags have been added
        assert updated_tag_count > initial_tag_count, "No new tags were added."

        # Verify that all tags, including the new ones, have the same style
        # This is a simplified check assuming all tags must have a specific class indicating their style (e.g., "chip-style")
        # In a real test, you might need to check for more specific style attributes or properties
        all_tags_have_chip_style = page.locator("[data-testid='tag-chip'].chip-style").count() == updated_tag_count
        assert all_tags_have_chip_style, "Not all tags match the expected 'chip' style."

    except Exception:
        page.screenshot(path="failure_test_new_tags_match_existing_ui_elements.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_new_tags_match_existing_ui_elements(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/new_tags_match_existing_ui_elements_20260218_155009.png")
        _exit = 1
    sys.exit(_exit)
