import sys, traceback, os
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: HAPPY_PATH - Successfully auto-populating additional tags after initial filter
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    )
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_auto_populate_tags_after_initial_filter(page):

    try:
        # Navigate to the base URL and wait for the page to load
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Login to the application
        _login(page)

        # Navigate to the filter panel and select Tag A
        page.locator("[data-testid='filter-panel']").locator("button", name="Tag A").click()
        page.wait_for_load_state("networkidle")

        # Assert that assets related to Tag A are displayed
        assets_displayed = page.locator("[data-testid='assets-related-to-tag']").count()
        assert assets_displayed > 0, f"Expected assets related to Tag A, but found {assets_displayed}"

        # Assert that additional tags present on these assets are auto-populated in the filter panel
        additional_tags_count = page.locator("[data-testid='additional-tags']").count()
        assert additional_tags_count > 0, "Expected additional tags to be auto-populated in the filter panel"

    except Exception:
        page.screenshot(path="failure_test_auto_populate_tags_after_initial_filter.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_auto_populate_tags_after_initial_filter(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/auto_populate_tags_after_initial_filter_20260217_101337.png")
        _exit = 1
    sys.exit(_exit)
