import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: STATE_PERSISTENCE - User-selected tags remain highlighted after async refresh
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


def _precondition(page):
    """
    Runs the configured PRECONDITION_STEPS before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.PRECONDITION_STEPS — change in .env, no code edits.
    """
    pass  # No precondition steps configured


def test_user_selected_tags_persist_after_refresh(page):

    try:
        _login(page)
        _precondition(page)

        # Select a tag from the filter panel
        tag_to_select = "Tag A"
        page.locator(f"text={tag_to_select}").click()
        page.wait_for_load_state("networkidle")

        # Verify the tag is selected/highlighted
        assert page.locator(f"text={tag_to_select}").get_attribute("aria-selected") == "true", f"{tag_to_select} should be selected"

        # Trigger an async refresh or navigate away and back
        page.reload()
        page.wait_for_load_state("networkidle")

        # Verify the tag remains selected/highlighted after the refresh
        assert page.locator(f"text={tag_to_select}").get_attribute("aria-selected") == "true", f"{tag_to_select} should remain selected after refresh"

    except Exception:
        page.screenshot(path="failure_test_user_selected_tags_persist_after_refresh.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_user_selected_tags_persist_after_refresh(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/user_selected_tags_persist_after_refresh_20260218_112810.png")
        _exit = 1
    sys.exit(_exit)
