import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

"""
Test: STATE_PERSISTENCE - Filter panel state after applying OR operator
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper â€” works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when multiple buttons match the pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")


def test_filter_panel_state_persistence(page):

    try:
        # Navigate to the base URL and wait for the network to be idle
        page.goto(settings.BASE_URL)
        page.wait_for_load_state("networkidle")

        # Perform login
        _login(page)

        # Navigate to the page where the filter panel is located
        # Assuming the filter panel is on a specific page, replace 'filter_page' with the actual path
        page.goto(f"{settings.BASE_URL}/filter_page")
        page.wait_for_load_state("networkidle")

        # Apply a filter
        # Assuming there's a way to select a filter, replace 'filter_option' with the actual filter option
        page.locator("[data-testid='filter-option']").click()

        # Select the OR operator
        # Assuming there's a specific button or element to apply the OR operator, replace 'or_operator' with the actual element
        page.locator("[data-testid='or-operator']").click()

        # Wait for the filter panel to reload
        page.wait_for_load_state("networkidle")

        # Verify the filter panel state is retained after applying the OR operator
        # This includes checking if the filter previously applied is still selected
        assert page.locator("[data-testid='filter-option']").is_checked(), "Filter option should be retained"
        assert page.locator("[data-testid='or-operator']").is_checked(), "OR operator should be retained"

    except Exception:
        page.screenshot(path="failure_test_filter_panel_state_persistence.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(300000)
            page = _ctx.new_page()
            _page = page
            try:
                test_filter_panel_state_persistence(page)
            finally:
                _ctx.close(); _browser.close()
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/filter_panel_state_persistence_20260217_133524.png")
        _exit = 1
    sys.exit(_exit)
