import sys, traceback, os
sys.path.insert(0, 'C:\\Users\\laksh\\qa_testing_agent_complete_v3.0_final\\outputs\\qa_testing_agent')  # ensure project root is importable
from playwright.sync_api import sync_playwright, expect
import re

_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass

def _dump_debug():
    global _page
    if not _page:
        return
    try:
        _page.wait_for_load_state('domcontentloaded', timeout=2000)
    except Exception:
        pass
    try:
        print(f"DEBUG_URL: {_page.url}")
    except Exception:
        pass

"""
Test: ERROR_FAILURE - Handle Filter Reload Failure Gracefully
Generated by QA Testing Agent
"""

import sys
import traceback
import os
import re
import time
from config.settings import settings


_page = None

def _take_screenshot(path):
    global _page
    if _page:
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            _page.screenshot(path=path, full_page=True)
            print(f"SCREENSHOT: {path}")
        except Exception:
            pass


def _login(page):
    """
    Generic login helper - works for any app with an Email/Password form.
    All values come from settings; no credentials are hardcoded.

    After login, navigates to settings.FEATURE_URL if configured so that
    every test starts on the correct page without repeating navigation.
    Uses .first on the button locator to survive strict-mode when multiple
    buttons match the login pattern.
    """
    page.goto(settings.BASE_URL)
    page.wait_for_load_state("networkidle")
    page.get_by_label(settings.EMAIL_FIELD_LABEL).fill(settings.LOGIN_EMAIL)
    page.get_by_label(settings.PASSWORD_FIELD_LABEL).fill(settings.LOGIN_PASSWORD)
    # .first avoids strict-mode error when 2+ buttons match the login pattern
    login_btn = page.get_by_role(
        "button",
        name=re.compile(settings.LOGIN_BUTTON_PATTERN, re.IGNORECASE),
    ).first
    expect(login_btn).to_be_visible(timeout=settings.ELEMENT_TIMEOUT_MS)
    expect(login_btn).to_be_enabled()
    login_btn.click()
    page.wait_for_load_state("networkidle")
    # Navigate to the feature page if one is configured
    if settings.FEATURE_URL and settings.FEATURE_URL != settings.BASE_URL:
        page.goto(settings.FEATURE_URL)
        page.wait_for_load_state("networkidle")


# ── App Helper Library (auto-generated from recorded_flow.py) ────────
# Regenerated automatically whenever recorded_flow.py changes.
# The LLM calls these helpers — it never writes raw selectors.


def _app_navigate_to(page, section: str):
    """Navigate to a section by its link name. Known sections: Folders, Tag
Cloud, Workflows, Products, Analytics"""
    page.get_by_role("link", name=section).click()
    page.wait_for_load_state("networkidle")

def _app_open_filters_section(page):
    """Open/expand the 'Filters' section. Source: page.locator("#rc-tabs-0-tab-
filters div").filter(has_text=re.compile(r"^Filters$")).click()"""
    page.locator("#rc-tabs-0-tab-filters div").filter(
        has_text=re.compile(r"^Filters$")
    ).first.click()
    page.wait_for_load_state("networkidle")

def _app_open_tags_section(page):
    """Open/expand the 'Tags' section. Source:
page.locator("a").filter(has_text="Tags").click()"""
    page.locator("a").filter(
        has_text=re.compile(r"^Tags$")
    ).first.click()
    page.wait_for_load_state("networkidle")

def _app_open_filter_panel(page):
    """Open the filter panel and expand the default section. Calls the
individual filter helpers generated from the recording."""
    _app_open_filters_section(page)
    _app_open_tags_section(page)

def _app_search(page, query: str):
    """Type a search/filter query. Source selector: #rc_select_6"""
    page.locator("#rc_select_6").click()
    page.locator("#rc_select_6").fill(query)
    page.wait_for_load_state("networkidle")

def _app_apply_or_operator(page, nth: int = 0):
    """Click the OR operator button. nth=0 for first, nth=N for subsequent."""
    if nth == 0:
        page.get_by_text("OR", exact=True).click()
    else:
        page.get_by_text("OR").nth(nth).click()
    page.wait_for_load_state("networkidle")

def _app_click_tag(page, tag_name: str):
    """Click a tag filter item by name only (count suffix is ignored). Tags
display as name+count e.g. 'toys59'. Sample names from recording: Delete
Asset, Vehicles, Lakshmi, Mr Cuddles, EN"""
    page.get_by_text(re.compile(rf"^{re.escape(tag_name)}\d+$")).first.click()
    page.wait_for_load_state("networkidle")

def _app_get_visible_tags(page):
    """Return list of tag names (without count) visible in the tag panel."""
    try:
        elems = page.locator("a").filter(
            has_text=re.compile(r"^\w[\w\s]+\d+$")
        ).all()
        return [
            re.sub(r"\d+$", "", e.inner_text(timeout=2000).strip()).strip()
            for e in elems
        ]
    except Exception:
        return []

def _app_get_result_count(page):
    """Read the total result count from a 'Total N items' label. Returns 0 if
not found."""
    try:
        text = page.get_by_text(
            re.compile(r"Total \d+ items")
        ).first.inner_text(timeout=5000)
        m = re.search(r"(\d+)", text)
        return int(m.group(1)) if m else 0
    except Exception:
        return 0

def _app_assert_result_count(page, expected: int, msg: str = ''):
    """Assert the total result count equals expected."""
    actual = _app_get_result_count(page)
    assert actual == expected, (
        f"{msg or 'Result count'}: expected {expected}, got {actual}"
    )

def _app_open_asset(page, index: int = 0):
    """Click a thumbnail to open an asset. index=0 for the first."""
    page.get_by_role("img", name="thumb").nth(index).click()
    page.wait_for_load_state("networkidle")

def _app_click_asset_tab(page, tab_name: str):
    """Click an asset detail tab by name. Known tabs: References, Folders"""
    page.get_by_role("tab", name=tab_name).click()
    page.wait_for_load_state("networkidle")

def _app_clear_search(page):
    """Clear Search"""
    page.get_by_text("Clear Search").click()
    page.wait_for_load_state("networkidle")

# ── End App Helper Library ───────────────────────────────────────────

def _precondition(page):
    """
    Runs the configured STORY_PRECONDITIONS_JSON steps before each test.
    These steps navigate the UI to the correct state (e.g. open the filter
    panel, expand the Tags section) so the test starts from the right place.
    Generated from settings.STORY_PRECONDITIONS_JSON — change in .env, no code edits.
    """
    # Click Filters
    page.locator("#rc-tabs-0-tab-filters div").filter(has_text=re.compile(r"^Filters$")).first.click()
    page.wait_for_load_state("networkidle")
    # Click Tags
    page.locator("a").filter(has_text="Tags").first.click()
    page.wait_for_load_state("networkidle")
    # Click tag toys
    page.get_by_role("link", name="Tag Cloud").click()
    page.wait_for_load_state("networkidle")
    # Click OR
    _app_apply_or_operator(page)
    page.wait_for_load_state("networkidle")


def test_handle_filter_reload_failure_gracefully(page):

    try:
        _login(page)
        _precondition(page)

        # Simulate a network failure during filter reload
        page.route("**/api/**", lambda r: r.abort("failed"))

        # Attempt to reload filters
        page.get_by_role("button", name="Reload Filters").click()
        page.wait_for_load_state("networkidle")

        # Verify that a nonintrusive error message is displayed
        error_message = page.get_by_text("Network error occurred", exact=False)
        expect(error_message).to_be_visible()

        # Verify that the user's filter selections are preserved
        selected_tag = page.get_by_role("checkbox", name="toys")
        expect(selected_tag).to_be_checked()

    except Exception:
        page.screenshot(path="failure_test_handle_filter_reload_failure_gracefully.png")
        raise

if __name__ == "__main__":
    _exit = 0
    try:
        with sync_playwright() as _pw:
            _browser = _pw.chromium.launch(headless=False)
            _ctx = _browser.new_context(
                viewport={"width": 1280, "height": 720},
                ignore_https_errors=True,
            )
            _ctx.set_default_timeout(10000)
            page = _ctx.new_page()
            _page = page
            page.on('framenavigated', lambda frame: print(f"NAVIGATED: {frame.url}", flush=True) if frame == page.main_frame else None)
            page.on('console', lambda msg: print(f"CONSOLE: {msg.type} {msg.text}", flush=True))
            page.on('pageerror', lambda err: print(f"PAGEERROR: {err}", flush=True))
            print(f"START_URL: {page.url}", flush=True)
            try:
                test_handle_filter_reload_failure_gracefully(page)
            except Exception:
                _take_screenshot(r"C:/Users/laksh/qa_testing_agent_complete_v3.0_final/outputs/qa_testing_agent/reports/screenshots/handle_filter_reload_failure_gracefully_20260223_144119.png")
                raise
            finally:
                try: _ctx.close()
                except Exception: pass
                try: _browser.close()
                except Exception: pass
        print("TEST_STATUS: PASSED")
    except Exception as _e:
        print("TEST_STATUS: FAILED")
        print(f"ERROR: {_e}")
        traceback.print_exc()
        _exit = 1
    sys.exit(_exit)
